/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GameControllerGetHistoryParams,
  GameResponseDto,
  PaginatedGameHistoryDto
} from '../../models';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Create a new game against the AI
 */
export const gameControllerCreateAiGame = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GameResponseDto>(
      {url: `/game/create-ai`, method: 'POST', signal
    },
      options);
    }




export const getGameControllerCreateAiGameMutationKey = () => ['gameControllerCreateAiGame'] as const;

export const getGameControllerCreateAiGameMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof gameControllerCreateAiGame>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof gameControllerCreateAiGame>>, TError,void, TContext> => {

const mutationKey = getGameControllerCreateAiGameMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof gameControllerCreateAiGame>>, void> = () => {


          return  gameControllerCreateAiGame(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GameControllerCreateAiGameMutationResult = NonNullable<Awaited<ReturnType<typeof gameControllerCreateAiGame>>>

    export type GameControllerCreateAiGameMutationError = unknown


    /**
 * @summary Create a new game against the AI
 */
export const useGameControllerCreateAiGame = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof gameControllerCreateAiGame>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof gameControllerCreateAiGame>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGameControllerCreateAiGameMutationOptions(options), queryClient);
    }
    /**
 * @summary Get paginated game history of a particular user
 */
export const gameControllerGetHistory = (
    params?: GameControllerGetHistoryParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PaginatedGameHistoryDto>(
      {url: `/game/history`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGameControllerGetHistoryQueryKey = (params?: GameControllerGetHistoryParams,) => {
    return [
    `/game/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getGameControllerGetHistoryQueryOptions = <TData = Awaited<ReturnType<typeof gameControllerGetHistory>>, TError = unknown>(params?: GameControllerGetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGameControllerGetHistoryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof gameControllerGetHistory>>> = ({ signal }) => gameControllerGetHistory(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GameControllerGetHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof gameControllerGetHistory>>>
export type GameControllerGetHistoryQueryError = unknown


export function useGameControllerGetHistory<TData = Awaited<ReturnType<typeof gameControllerGetHistory>>, TError = unknown>(
 params: undefined |  GameControllerGetHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gameControllerGetHistory>>,
          TError,
          Awaited<ReturnType<typeof gameControllerGetHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGameControllerGetHistory<TData = Awaited<ReturnType<typeof gameControllerGetHistory>>, TError = unknown>(
 params?: GameControllerGetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gameControllerGetHistory>>,
          TError,
          Awaited<ReturnType<typeof gameControllerGetHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGameControllerGetHistory<TData = Awaited<ReturnType<typeof gameControllerGetHistory>>, TError = unknown>(
 params?: GameControllerGetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get paginated game history of a particular user
 */

export function useGameControllerGetHistory<TData = Awaited<ReturnType<typeof gameControllerGetHistory>>, TError = unknown>(
 params?: GameControllerGetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGameControllerGetHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






