/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GameControllerGetHistoryParams,
  GameResponseDto,
  PaginatedGameHistoryDto
} from '../../models';

import { customInstance } from '../../custom-instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type gameControllerCreateAiGameResponse201 = {
  data: GameResponseDto
  status: 201
}

export type gameControllerCreateAiGameResponseSuccess = (gameControllerCreateAiGameResponse201) & {
  headers: Headers;
};
;

export type gameControllerCreateAiGameResponse = (gameControllerCreateAiGameResponseSuccess)

export const getGameControllerCreateAiGameUrl = () => {




  return `/game/create-ai`
}

/**
 * @summary Create a new game against the AI
 */
export const gameControllerCreateAiGame = async ( options?: RequestInit): Promise<gameControllerCreateAiGameResponse> => {

  return customInstance<gameControllerCreateAiGameResponse>(getGameControllerCreateAiGameUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getGameControllerCreateAiGameMutationKey = () => ['gameControllerCreateAiGame'] as const;

export const getGameControllerCreateAiGameMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof gameControllerCreateAiGame>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof gameControllerCreateAiGame>>, TError,void, TContext> => {

const mutationKey = getGameControllerCreateAiGameMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof gameControllerCreateAiGame>>, void> = () => {


          return  gameControllerCreateAiGame()
        }






  return  { mutationFn, ...mutationOptions }}

    export type GameControllerCreateAiGameMutationResult = NonNullable<Awaited<ReturnType<typeof gameControllerCreateAiGame>>>

    export type GameControllerCreateAiGameMutationError = unknown


    /**
 * @summary Create a new game against the AI
 */
export const useGameControllerCreateAiGame = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof gameControllerCreateAiGame>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof gameControllerCreateAiGame>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGameControllerCreateAiGameMutationOptions(options), queryClient);
    }
    export type gameControllerGetHistoryResponse200 = {
  data: PaginatedGameHistoryDto
  status: 200
}

export type gameControllerGetHistoryResponseSuccess = (gameControllerGetHistoryResponse200) & {
  headers: Headers;
};
;

export type gameControllerGetHistoryResponse = (gameControllerGetHistoryResponseSuccess)

export const getGameControllerGetHistoryUrl = (params?: GameControllerGetHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/game/history?${stringifiedParams}` : `/game/history`
}

/**
 * @summary Get paginated game history of a particular user
 */
export const gameControllerGetHistory = async (params?: GameControllerGetHistoryParams, options?: RequestInit): Promise<gameControllerGetHistoryResponse> => {

  return customInstance<gameControllerGetHistoryResponse>(getGameControllerGetHistoryUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGameControllerGetHistoryQueryKey = (params?: GameControllerGetHistoryParams,) => {
    return [
    `/game/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getGameControllerGetHistoryQueryOptions = <TData = Awaited<ReturnType<typeof gameControllerGetHistory>>, TError = unknown>(params?: GameControllerGetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGameControllerGetHistoryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof gameControllerGetHistory>>> = ({ signal }) => gameControllerGetHistory(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GameControllerGetHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof gameControllerGetHistory>>>
export type GameControllerGetHistoryQueryError = unknown


export function useGameControllerGetHistory<TData = Awaited<ReturnType<typeof gameControllerGetHistory>>, TError = unknown>(
 params: undefined |  GameControllerGetHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gameControllerGetHistory>>,
          TError,
          Awaited<ReturnType<typeof gameControllerGetHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGameControllerGetHistory<TData = Awaited<ReturnType<typeof gameControllerGetHistory>>, TError = unknown>(
 params?: GameControllerGetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gameControllerGetHistory>>,
          TError,
          Awaited<ReturnType<typeof gameControllerGetHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGameControllerGetHistory<TData = Awaited<ReturnType<typeof gameControllerGetHistory>>, TError = unknown>(
 params?: GameControllerGetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get paginated game history of a particular user
 */

export function useGameControllerGetHistory<TData = Awaited<ReturnType<typeof gameControllerGetHistory>>, TError = unknown>(
 params?: GameControllerGetHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gameControllerGetHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGameControllerGetHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






