/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  GameResponseDto,
  PaginatedGameHistoryDto
} from '../../models';


export const getGameControllerCreateAiGameResponseMock = (overrideResponse: Partial<Extract<GameResponseDto, object>> = {}): GameResponseDto => ({id: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', status: faker.helpers.arrayElement(['IN_PROGRESS','FINISHED','DRAW','ABANDONED'] as const), winnerId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), boardStateJson: faker.string.alpha({length: {min: 10, max: 20}}), whitePlayerId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), blackPlayerId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), ...overrideResponse})

export const getGameControllerGetHistoryResponseMock = (overrideResponse: Partial<Extract<PaginatedGameHistoryDto, object>> = {}): PaginatedGameHistoryDto => ({games: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', status: faker.helpers.arrayElement(['IN_PROGRESS','FINISHED','DRAW','ABANDONED'] as const), winnerId: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]), boardStateJson: faker.string.alpha({length: {min: 10, max: 20}}), whitePlayerId: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]), blackPlayerId: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined])})), total: faker.number.float({fractionDigits: 2}), page: faker.number.float({fractionDigits: 2}), totalPages: faker.number.float({fractionDigits: 2}), ...overrideResponse})

