/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GameResponseDto,
  PaginatedGameHistoryDto
} from '../../models';

import {
  getGameControllerCreateAiGameResponseMock,
  getGameControllerGetHistoryResponseMock
} from './game.faker';

export { getGameControllerCreateAiGameResponseMock, getGameControllerGetHistoryResponseMock } from './game.faker';


export const getGameControllerCreateAiGameMockHandler = (overrideResponse?: GameResponseDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GameResponseDto> | GameResponseDto), options?: RequestHandlerOptions) => {
  return http.post('*/game/create-ai', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGameControllerCreateAiGameResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGameControllerGetHistoryMockHandler = (overrideResponse?: PaginatedGameHistoryDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PaginatedGameHistoryDto> | PaginatedGameHistoryDto), options?: RequestHandlerOptions) => {
  return http.get('*/game/history', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGameControllerGetHistoryResponseMock(),
      { status: 200
      })
  }, options)
}
export const getGameMock = () => [
  getGameControllerCreateAiGameMockHandler(),
  getGameControllerGetHistoryMockHandler()
]
