/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  LoginResponseDto,
  UserEntity
} from '../../models';

import {
  getAuthControllerLoginResponseMock,
  getAuthControllerRegisterResponseMock
} from './auth.faker';

export { getAuthControllerRegisterResponseMock, getAuthControllerLoginResponseMock } from './auth.faker';


export const getAuthControllerRegisterMockHandler = (overrideResponse?: UserEntity | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserEntity> | UserEntity), options?: RequestHandlerOptions) => {
  return http.post('*/auth/register', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAuthControllerRegisterResponseMock(),
      { status: 201
      })
  }, options)
}

export const getAuthControllerLoginMockHandler = (overrideResponse?: LoginResponseDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<LoginResponseDto> | LoginResponseDto), options?: RequestHandlerOptions) => {
  return http.post('*/auth/login', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAuthControllerLoginResponseMock(),
      { status: 200
      })
  }, options)
}
export const getAuthMock = () => [
  getAuthControllerRegisterMockHandler(),
  getAuthControllerLoginMockHandler()
]
