/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  LoginResponseDto,
  UserEntity
} from '../../models';


export const getAuthControllerRegisterResponseMock = (overrideResponse: Partial<Extract<UserEntity, object>> = {}): UserEntity => ({email: faker.string.alpha({length: {min: 10, max: 20}}), username: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getAuthControllerLoginResponseMock = (overrideResponse: Partial<Extract<LoginResponseDto, object>> = {}): LoginResponseDto => ({access_token: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

