/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import type { CreateAiGameDtoSide } from './createAiGameDtoSide';

export interface CreateAiGameDto {
  /** Side the human player wants to play as. Defaults to WHITE when omitted. */
  side?: CreateAiGameDtoSide;
}
