/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import type { GameResponseDtoStatus } from './gameResponseDtoStatus';

export interface GameResponseDto {
  /** Unique identifier of the game */
  id: string;
  createdAt: string;
  updatedAt: string;
  status: GameResponseDtoStatus;
  /** @nullable */
  winnerId: string | null;
  /** Serialized board state */
  boardStateJson: string;
  /** @nullable */
  whitePlayerId: string | null;
  /** @nullable */
  blackPlayerId: string | null;
}
