/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import type { GameHistoryItemDtoBlackPlayerId } from './gameHistoryItemDtoBlackPlayerId';
import type { GameHistoryItemDtoStatus } from './gameHistoryItemDtoStatus';
import type { GameHistoryItemDtoWhitePlayerId } from './gameHistoryItemDtoWhitePlayerId';
import type { GameHistoryItemDtoWinnerId } from './gameHistoryItemDtoWinnerId';

export interface GameHistoryItemDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  status: GameHistoryItemDtoStatus;
  /** @nullable */
  winnerId?: GameHistoryItemDtoWinnerId;
  boardStateJson: string;
  /** @nullable */
  whitePlayerId?: GameHistoryItemDtoWhitePlayerId;
  /** @nullable */
  blackPlayerId?: GameHistoryItemDtoBlackPlayerId;
}
