/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import type { GameHistoryItemDtoStatus } from './gameHistoryItemDtoStatus';

export interface GameHistoryItemDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  status: GameHistoryItemDtoStatus;
  /** @nullable */
  winnerId?: string | null;
  boardStateJson: string;
  /** @nullable */
  whitePlayerId?: string | null;
  /** @nullable */
  blackPlayerId?: string | null;
}
