/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type GameHistoryItemDtoWhitePlayerId = { [key: string]: unknown } | null;
