/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */

export type GameHistoryItemDtoStatus = typeof GameHistoryItemDtoStatus[keyof typeof GameHistoryItemDtoStatus];


export const GameHistoryItemDtoStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
  DRAW: 'DRAW',
  ABANDONED: 'ABANDONED',
} as const;
