/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */

export interface LoginResponseDto {
  /** JWT Access Token */
  access_token: string;
}
