/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** Unique email of the user */
  email: string;
  password: string;
}
