/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */
import type { GameHistoryItemDto } from './gameHistoryItemDto';

export interface PaginatedGameHistoryDto {
  games: GameHistoryItemDto[];
  total: number;
  page: number;
  totalPages: number;
}
