/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Warcabownik
 * Checkers model with database and API for managing games
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** Unique email of the user */
  email: string;
  /** Strong user password (min 10 length, min 1 number, min 1 lowercase, min 1 symbol, min 1 uppercase) */
  password: string;
  /** Username of the user */
  username: string;
}
