
@baseUrl = http://localhost:3000/auth
###
POST {{baseUrl}}/register
Content-Type: application/json

{
  "email": "contact@example.com",
  "password": "i-DO-pieca67",
  "firstName": "Robert",
  "lastName": "Makłowicz",
  "phoneNumber": "+48123456789"
}

###

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "contact@example.com",
    "password": "i-DO-pieca67"
}
